services:
  inventory-db:
    image: postgres:alpine
    container_name: inventory-db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 1s
      timeout: 1s
      retries: 15
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    env_file:
      - .env.docker

  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    depends_on:
      - inventory-db
    links:
      - inventory-db
    ports:
      - '3004:3000'
    env_file:
      - .env.docker
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma

volumes:
  inventory-db-data: